branch-defaults:
  default:
    environment: null
    group_suffix: null
  main:
    environment: null
global:
  application_name: task_manager
  branch: null
  default_ec2_keyname: Docker
  default_platform: Python 3.13 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  security_groups: sg-0c679431e0b1385d5
  workspace_type: Application
