name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install EB CLI
        run: pip install awsebcli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create or Update EB Environment
        run: |
          APP_NAME=${{ secrets.EB_APP_NAME }}
          ENV_NAME=${{ secrets.EB_ENV_NAME }}

          # Check if env exists
          ENV_EXISTS=$(aws elasticbeanstalk describe-environments \
            --application-name "$APP_NAME" \
            --environment-names "$ENV_NAME" \
            --query 'Environments' --output text)

          if [ -z "$ENV_EXISTS" ]; then
            echo "Environment not found. Creating..."
            eb create "$ENV_NAME" --single --instance_type t3.small
          else
            echo "Environment exists. Deploying update..."
            eb deploy "$ENV_NAME"
          fi

