name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install EB CLI
        run: pip install awsebcli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Debug EB Environments
        run: |
          aws elasticbeanstalk describe-environments --region ${{ secrets.AWS_REGION }} \
            --query 'Environments[*].{App:ApplicationName,Env:EnvironmentName,Status:Status}'


      - name: Deploy to Elastic Beanstalk
        run: |
          eb init ${{ secrets.EB_APP_NAME }} -p python-3.11 --region ${{ secrets.AWS_REGION }}
          eb use ${{ secrets.EB_ENV_NAME }}
          eb deploy

